version: "3.9"
services:
  web:
    image: "${IMAGE:-ghcr.io/OWNER/REPO:latest}"
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    restart: unless-stopped
