version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: sh -c "npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
