app = "YOUR_FLY_APP_NAME"
primary_region = "iad"
kill_signal = "SIGINT"

[build]
  image = "ghcr.io/OWNER/REPO:latest"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
